import { db } from "@/lib/firebase";
import { collection, getDocs, addDoc } from "firebase/firestore";

export type Customer = {
    id: string;
    name: string;
    phone: string;
    email?: string;
    idNumber?: string; // Cédula
    taxId?: string; // RNC
    company?: string;
};

// Omit 'id' for new customers as it will be auto-generated by Firestore
export type NewCustomer = Omit<Customer, 'id'>;

export async function getCustomers(): Promise<Customer[]> {
    const customersCol = collection(db, 'customers');
    const customerSnapshot = await getDocs(customersCol);
    const customerList = customerSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as Customer));
    return customerList;
}

export async function addCustomer(customerData: NewCustomer): Promise<Customer> {
    const customersCol = collection(db, 'customers');
    const docRef = await addDoc(customersCol, customerData);
    return { id: docRef.id, ...customerData };
}
